# Start with the official Ruby image
FROM ruby:3.4-slim


RUN apt-get update -y && apt-get install -y --no-install-recommends \
    libyaml-dev pkg-config build-essential git curl ca-certificates libpq-dev libvips\
 && curl -fsSL https://deb.nodesource.com/setup_lts.x -o /tmp/nodesource.sh \
 && bash /tmp/nodesource.sh \
 && apt-get install -y --no-install-recommends nodejs \
 && rm -rf /var/lib/apt/lists/* /tmp/nodesource.sh

 # Install Rails
RUN gem install rails
